import forms from '@tailwindcss/forms'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f9f9f9',
        'on-secondary': '#ffffff',
        'on-error': '#ffffff',
        'on-surface-variant': '#5b4039',
        secondary: '#5f5e5e',
        'on-tertiary': '#ffffff',
        'secondary-container': '#e2dfde',
        'on-primary-fixed-variant': '#862200',
        'surface-container': '#eeeeee',
        'outline-variant': '#e4beb4',
        'primary-container': '#ff5722',
        'on-primary-container': '#541200',
        'on-secondary-container': '#636262',
        'on-background': '#1a1c1c',
        'surface-container-high': '#e8e8e8',
        'surface-tint': '#b02f00',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#f4fffa',
        'on-tertiary-fixed-variant': '#005145',
        'on-error-container': '#93000a',
        error: '#ba1a1a',
        'on-surface': '#1a1c1c',
        'inverse-on-surface': '#f1f1f1',
        'surface-dim': '#dadada',
        'primary-fixed-dim': '#ffb5a0',
        'surface-bright': '#f9f9f9',
        'inverse-primary': '#ffb5a0',
        'surface-container-highest': '#e2e2e2',
        'tertiary-container': '#008471',
        background: '#f9f9f9',
        'error-container': '#ffdad6',
        'secondary-fixed': '#e5e2e1',
        'surface-variant': '#e2e2e2',
        tertiary: '#006859',
        'surface-container-low': '#f3f3f3',
        'secondary-fixed-dim': '#c8c6c5',
        'surface-container-lowest': '#ffffff',
        primary: '#b02f00',
        'primary-fixed': '#ffdbd1',
        'on-secondary-fixed': '#1b1c1c',
        'tertiary-fixed-dim': '#44ddc1',
        'on-tertiary-fixed': '#00201a',
        'inverse-surface': '#2f3131',
        outline: '#907067',
        'tertiary-fixed': '#68fadd',
        'on-primary-fixed': '#3b0900',
        'on-secondary-fixed-variant': '#474746',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        'margin-mobile': '16px',
        'container-max': '1200px',
        unit: '4px',
        gutter: '24px',
      },
      fontFamily: {
        'body-lg': ['Be Vietnam Pro'],
        'headline-md': ['Be Vietnam Pro'],
        'label-md': ['Be Vietnam Pro'],
        'headline-lg': ['Be Vietnam Pro'],
        'title-md': ['Be Vietnam Pro'],
        'body-md': ['Be Vietnam Pro'],
        'price-lg': ['Be Vietnam Pro'],
        'title-lg': ['Be Vietnam Pro'],
        'headline-lg-mobile': ['Be Vietnam Pro'],
        'display-lg': ['Be Vietnam Pro'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'label-md': [
          '12px',
          { lineHeight: '16px', letterSpacing: '0.01em', fontWeight: '500' },
        ],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'price-lg': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '30px', fontWeight: '700' }],
        'display-lg': [
          '40px',
          { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
      },
    },
  },
  plugins: [forms],
}
